<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 25.06.2019
 * Time: 09:47
 */
?>
<h2><?=$this->translate('update avatar for category')?> <?=$oCategory->getLabel()?></h2>
<form action="" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="avatar">Avatar (.png)</label>
        <input type="file" name="avatar" accept="image/png" class="form-control">
    </div>
    <div class="form-group">
        <input type="hidden" name="category_idfs" value="<?=$oCategory->getID()?>" />
        <input type="submit" class="btn btn-success" value="<?=$this->translate('Update avatar')?>" />
    </div>
</form>