<?php
/**
 * add.phtml - Add Room
 *
 * View File for Add Room Form
 *
 * @category View
 * @package Room
 * @author Nathanael Kammermann
 * @copyright (C) 2019 Nathanael Kammermann <nathanael.kammermann@gmail.com>
 * @license https://opensource.org/licenses/BSD-3-Clause
 * @version 1.0
 * @since File available since Version 1.0
 */

if($sMode == 'closemodal') {
    ?>
    <script>
        //$('#exampleModalCenter').modal('toggle');
    </script>
    <?php
} else {

$title = $this->translate('Add Event');
$this->headTitle($title);
?>
<form action="/calendar/event/add" method="POST">
    <?php if($sMode == 'modal') { ?>
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle"><?=$title?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
    <?php } else { ?>
    <div class="card">
        <div class="card-header">
            <h2 class="card-title"><?=$title?></h2>
        </div>
        <div class="card-body row">
            <div class="col-md-8">
    <?php } ?>
            <div class="row">
                <div class="form-group col-md-3">
                    <label for="calendar_idfs"><?=$this->translate('Calendar')?></label>
                    <select name="calendar_idfs" class="form-control">
                        <?php foreach($aCalendars as $oCal) { ?>
                            <option value="<?=$oCal->getID()?>"<?=($iCalendarSelected == $oCal->getID()) ? ' selected="selected"' : ''?>>
                                <?=$oCal->getLabel()?>
                            </option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group <?=($sMode == 'modal') ? 'col-md-8' : 'col-md-4'?>">
                    <label for="date_start"><?=$this->translate('Start')?></label>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="date" name="date_start" class="form-control" value="<?=($sDate != '') ? $sDate : date('Y-m-d',time())?>" />
                        </div>
                        <div class="col-md-6">
                            <input type="time" name="time_start" class="form-control" value="<?=($sTime != '') ? $sTime : ''?>" />
                        </div>
                    </div>
                </div>
                <div class="form-group <?=($sMode == 'modal') ? 'col-md-8' : 'col-md-4'?>">
                    <label for="date_start"><?=$this->translate('Ende')?></label>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="date" name="date_end" class="form-control" value="<?=($sDate != '') ? $sDate : date('Y-m-d',time())?>" />
                        </div>
                        <div class="col-md-6">
                            <input type="time" name="time_end" class="form-control" value="<?=($sTime != '') ? $sTime : ''?>" />
                        </div>
                    </div>
                </div>
                <div class="row <?=($sMode == 'modal') ? 'col-md-12' : 'col-md-5'?>">
                    <?php if(array_key_exists('task',$aPlugins)) { ?>
                        <div class="form-group col-md-4">
                            <label for="task_idfs"><?=$this->translate('Task')?></label>
                            <select class="form-control eventAddTask" name="task_idfs"></select>
                        </div>
                    <?php } ?>
                    <?php if(array_key_exists('resident',$aPlugins)) { ?>
                        <div class="form-group col-md-4">
                            <label for="resident_idfs"><?=$this->translate('Resident')?></label>
                            <select class="form-control eventAddResident" name="resident_idfs"></select>
                        </div>
                    <?php } ?>
                    <?php if(array_key_exists('room',$aPlugins)) { ?>
                        <div class="form-group col-md-4">
                            <label for="room_idfs"><?=$this->translate('Room')?></label>
                            <select class="form-control eventAddRoom" name="room_idfs"></select>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label for="label"><?=$this->translate('Titel')?></label>
                <input type="text" name="label" class="form-control" />
            </div>
            <div class="form-group">
                <label for="excerpt"><?=$this->translate('Auszug')?></label>
                <input type="text" name="excerpt" class="form-control" />
            </div>
            <div class="form-group">
                <label for="description"><?=$this->translate('Beschreibung')?></label>
                <textarea type="text" name="description" class="form-control">
                </textarea>
            </div>
        <?php if($sMode == 'modal') { ?>
        </div>
        <div class="modal-footer">
        <?php } else { ?>
        </div>
            <div class="col-md-4">
                <div id='calendar'></div>
            </div>
        </div>
        <div class="card-footer">
        <?php } ?>
            <input type="hidden" name="window_mode" value="<?=$sMode?>" />
            <input type="submit" class="btn btn-primary" value="<?=$this->translate('Save Event')?>" />
            <?php if($sMode == 'modal') { ?>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                 </div>
             </div>
            </div>
            <?php } else { ?>
                <a href="/calendar" title="<?=$this->translate('Cancel')?>" class="btn btn-danger">
                    <?=$this->translate('Cancel')?>
                </a>
        </div>
    </div>
            <?php } ?>

</form>
<script>
    <?php if($sMode != 'modal') {?>
    document.addEventListener('DOMContentLoaded', function() {
        var calendar = false;
        var previewEvent = false;
    <?php } ?>
    $('.eventAddTask').select2({
        ajax: {
            url: '/task/quicksearch',
            dataType: 'json'
        }
    });
    $('.eventAddResident').select2({
        ajax: {
            url: '/resident/quicksearch',
            dataType: 'json'
        }
    });
    $('.eventAddRoom').select2({
        ajax: {
            url: '/room/list',
            dataType: 'json'
        }
    });
    $("input[name^='date_start']").on('blur',function() {
        $("input[name^='date_end']").val($(this).val());
        calendar.gotoDate($(this).val());
    });
    $("input[name^='label']").on('blur',function() {
        var label = $(this).val();
        var date = $("input[name^='date_start']").val();
        var time = $("input[name^='time_start']").val();

        if(!previewEvent) {
            previewEvent = calendar.addEvent({ // this object will be "parsed" into an Event Object
                title: label, // a property!
                start: date + 'T' + time, // a property!
                color: 'red',
                end: date + 'T' + time // a property! ** see important note below about 'end' **
            },)
        } else {
            previewEvent.remove();
            previewEvent = calendar.addEvent({ // this object will be "parsed" into an Event Object
                title: label, // a property!
                start: date + 'T' + time, // a property!
                color: 'red',
                end: date + 'T' + time // a property! ** see important note below about 'end' **
            },)
        }
    });
    $('.eventAddTask').on('select2:select',function(e) {
        $("input[name^='label']").val(e.params.data.text);
    });
    <?php if($sMode != 'modal') {?>
        var calendarEl = document.getElementById('calendar');
        calendar = new FullCalendar.Calendar(calendarEl, {
            plugins: [ 'timeGrid' ],
            defaultView: 'timeGridDay',
            defaultDate: '<?=date('Y-m-d',time())?>',
            eventSources: <?=json_encode($aEventSources)?>
        });
        calendar.render();
    });
    <?php } ?>

    tinymce.init({
        selector: 'textarea',
        plugins: "lists fullscreen autolink link table wordcount",
        toolbar: "bullist link table formatselect forecolor backcolor wordcount fullscreen",
        default_link_target: "_blank",
        block_formats: 'Paragraph=p; Header 1=h1; Header 2=h2; Header 3=h3',
        paste_as_text: true,
        menubar: false
    });
</script>
<?php } ?>