<?php
?>
<form>
    <div class="row">
        <b>Start</b>
        <div class="form-group col-md-7">
            <label for="repeat_date">
                Datum
            </label>
            <input class="form-control" type="date" name="repeat_date" />
        </div>
        <div class="form-group col-md-3">
            <label for="repeat_time">
                Zeit
            </label>
            <input class="form-control" type="time" name="repeat_time" />
        </div>
    </div>
    <div class="row">
        <b>Ende</b>
        <div class="form-group col-md-7">
            <label for="repeat_date_end">
                Datum
            </label>
            <input class="form-control" type="date" name="repeat_date_end" />
        </div>
        <div class="form-group col-md-3">
            <label for="repeat_time_end">
                Zeit
            </label>
            <input class="form-control" type="time" name="repeat_time_end" />
        </div>
    </div>
    <input type="submit" class="btn btn-primary eventSaveRepeatModal" value="Wiederholung hinzufügen" />
</form>
<script>
    $('.eventSaveRepeatModal').on('click',function() {
        var oData = {};
        oData['event_idfs'] = <?=$oEvent->Event_ID?>;
        oData['date_start'] = $("input[name^='repeat_date']").val();
        oData['time_start'] = $("input[name^='repeat_time']").val();
        oData['date_end'] = $("input[name^='repeat_date_end']").val();
        oData['time_end'] = $("input[name^='repeat_time_end']").val();

        $.post('/calendar/event/saverepeat',oData,function(retVal) {
            $('.modal-body').html('<div class="alert alert-success">Wiederholung erfolgreich gespeichert</div>');
        });

        return false;
    });

    $('input[name^="repeat_date"]').on('blur',function() {
        var newDate = $(this).val();
        $('input[name^="repeat_date_end"]').val(newDate);
    });
</script>
