<?php
?>
<form>
    <div class="row">
        <div class="form-group col-md-7">
            <label for="ticket_label">
                Name
            </label>
            <input class="form-control" type="text" name="ticket_label" value="<?=$oEvent->label?> Standard Ticket" />
        </div>
        <div class="form-group col-md-3">
            <label for="ticket_price">
                Preis
            </label>
            <input class="form-control" type="text" name="ticket_price" value="0" />
        </div>
        <div class="form-group col-md-2">
            <label for="ticket_slots">
                Slots
            </label>
            <input class="form-control" type="number" name="ticket_slots" value="10" />
        </div>
    </div>
    <input type="submit" class="btn btn-primary eventSaveTicketModal" value="Ticket speichern" />
</form>
<script>
    $('.eventSaveTicketModal').on('click',function() {
        var oData = {};
        oData['event_idfs'] = <?=$oEvent->Event_ID?>;
        oData['label'] = $("input[name^='ticket_label']").val();
        oData['price'] = $("input[name^='ticket_price']").val();
        oData['slots'] = $("input[name^='ticket_slots']").val();

        $.post('/calendar/event/saveticket',oData,function(retVal) {
            $('.modal-body').html('<div class="alert alert-success">Ticket erfolgreich gespeichert</div>');
        });

        return false;
    });
</script>
