<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 19.03.2019
 * Time: 23:55
 */

$title = 'Delete event';
//$url   = $this->url('event', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($event->label) ?> <?= $this->escapeHtml($event->date_start) ?>" ?
</p>

<form action="/calendar/event/delete" method="post">
    <div class="form-group">
        <input type="hidden" name="goto_link" value="<?=$sGoTo?>" />
        <input type="hidden" name="id" value="<?= (int) $event->Event_ID ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>