<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 14.08.2019
 * Time: 08:53
 */
?>
<div class="row">
    <input type="hidden" name="quickedit_goto" value="<?=$sGoTo?>" />
    <div class="col-md-12">
        <small><b>Start</b></small>
    </div>
    <div class="col-md-7">
        <input class="form-control" type="date" name="quickedit_date" id="quickedit_date" value="<?=date('Y-m-d',strtotime($oEvent->date_start))?>" />
    </div>
    <div class="col-md-5">
        <input class="form-control" type="time" name="quickedit_time" id="quickedit_time" value="<?=date('H:i',strtotime($oEvent->date_start))?>" />
    </div>
    <div class="col-md-12">
        <small><b>Ende</b></small>
    </div>
    <div class="col-md-7">
        <input class="form-control" type="date" name="quickedit_date_end" id="quickedit_date_end" value="<?=date('Y-m-d',strtotime($oEvent->date_end))?>" />
    </div>
    <div class="col-md-5">
        <input class="form-control" type="time" name="quickedit_time_end" id="quickedit_time_end" value="<?=date('H:i',strtotime($oEvent->date_end))?>" />
    </div>
</div>

