<?php
?>
<h1>
    Wordpress Event Spotlight
</h1>
<ul class="list-group">
    <?php
    foreach($oEvents as $oEv) {
    ?>
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-4">
                <?=$oEv->label?>
            </div>
            <div class="col-md-3">
                <?=date('d.m.Y H:i',strtotime($oEv->date_start))?>
            </div>
            <div class="col-md-2">
                <a href="/calendar/event/togglewebspotlight/<?=$oEv->Event_ID?>">
                    <i class="fas fa-trash"></i>
                </a>
            </div>
        </div>
    </li>
    <?php } ?>
</ul>
