<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 14.08.2019
 * Time: 07:35
 */

setlocale(LC_ALL ,'de_DE','de');

?>
<div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="eventModalTitle"><?=$oEvent->label?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="/calendar/event/update" method="POST">
                <input type="hidden" id="quickEditID" name="event_id" value="<?=$oEvent->Event_ID?>" />
                <div class="modal-body">
                <div class="row">
                    <div class="col-md-1">
                        <i class="fas fa-clock"></i>
                    </div>
                    <div class="col-md-6 dateRow">
                        <?=$this->translate(strftime('%A, %d. %B %Y',strtotime($oEvent->date_start)))?> - <a href="/calendar/event/addrepeat/<?= $oEvent->Event_ID ?>" class="btn-modal-mode" data-hook-mode="html" data-hook-after="eventAddRepeatModal"><i class="fas fa-plus" title="Wiederholung hinzufügen"></i></a><br/>
                        <small><?=date('H:i',strtotime($oEvent->date_start))?> - <?=date('H:i',strtotime($oEvent->date_end))?> Uhr</small>
                         <br/>
                        <?php
                        if($oEvent->root_event_idfs != 0) { ?>
                        <small><i>Dies ist eine Wiederholung des Events vom <?=date('d.m.Y',strtotime($oRoot->date_start))?></i></small>
                        <?php } ?>
                        <?php
                        if(count($aChildren) > 0) {
                            ?>
                            <i>Dieses Event wiederholt sich am:</i><a class="eventEditRepeatModal" href="#"><i class="fas fa-edit" title="Wiederholungen bearbeiten"></i></a><br/>
                            <ul class="eventChildrenList" style="list-style-type: none; width:100%: display:inline-block; margin:0; padding:0;">
                            <?php
                            foreach($aChildren as $oChildEv) { ?>
                                <li style="position:relative; float:left; margin-right:2px;" data-child-id="<?=$oChildEv->Event_ID?>">
                                    <?=strftime('%d.%m.%Y - %H:%M',strtotime($oChildEv->date_start))?>&nbsp;|&nbsp;
                                </li>
                            <?php } ?>
                            </ul>
                            <?php
                        } ?>
                    </div>
                    <div class="col-md-5">
                        <?php if(count($aTickets) > 0) { ?>
                        <a href="/article/avatar/<?=$aTickets[0]->id?>" class="btn-modal-mode" data-hook-mode="html" data-hook-after="eventAddRepeatModal">
                            <img src="/data/article/<?=$aTickets[0]->id?>/avatar.png" style="max-width:100%; max-height:100px;"/>
                        </a>
                        <?php } ?>
                    </div>
                </div>
                <div class="row" style="margin-top:8px;">
                    <div class="col-md-1">
                        <i class="fas fa-info"></i>
                    </div>
                    <div class="col-md-11">
                        <i class="plc-calendar-event-excerpt-modal"><?=($oEvent->excerpt != '') ? $oEvent->excerpt : '-'?></i><br/>
                        <span class="plc-calendar-event-description-modal"><?=($oEvent->description != '') ? $oEvent->description : '-'?></span><br/>
                    </div>
                </div>
                <div class="row" style="margin-top:8px;">
                    <div class="col-md-1">
                        <i class="fas fa-users"></i>
                    </div>
                    <div class="col-md-11">
                        <b>Verfügbare Tickets - <a href="#<?=$oEvent->Event_ID?>" class="eventAddTicketModal"><small>Ticket erfassen</small></a></b><br/>
                        <?php if(count($aTickets) == 0) echo 'Keine'; ?>

                        <?php foreach($aTickets as $oTk) { ?>
                            <?=$oTk->label?> - <?='€ '.$oTk->price?> - <?=$oTk->slots_free.'/'.$oTk->slots_total?> - <a href="#<?=$oTk->id?>" class="eventTicketEditModal"><i class="fas fa-edit"></i></a>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <?php if($oEvent->event_confirm == 1) { ?>
                <a href="/calendar/event/confirm/<?=$oEvent->Event_ID?>" class="btn btn-success">
                    <i class="fas fa-check"></i> Erledigt
                </a>
                <?php } ?>
                <?php
                if(count($aTickets) > 0) {
                    if ($aTickets[0]->fully_booked == 0) { ?>
                        <a href="/calendar/event/tooglebooking/<?= $oEvent->Event_ID ?>"
                           class="btn btn-default btn-modal-mode" title="Event kann gebucht werden"
                           data-hook-after="eventToggleBookModal">
                            <i class="fas fa-door-open"></i>
                        </a>
                    <?php } else { ?>
                        <a href="/calendar/event/tooglebooking/<?= $oEvent->Event_ID ?>"
                           class="btn btn-default btn-modal-mode" title="Event ist ausgebucht"
                           data-hook-after="eventToggleBookModal">
                            <i class="fas fa-door-closed"></i>
                        </a>
                    <?php }
                }?>
                <?php
                if(array_key_exists('wordpress',$aPlugins)) {
                    $sIcon = 'fa-eye';
                    $sIconTitle = 'Wird auf Webseite angezeigt';
                    if($oEvent->web_show == 0) {
                        $sIcon = 'fa-eye-slash';
                        $sIconTitle = 'Wird nicht auf Webseite angezeigt';
                    }
                ?>
                <a href="/calendar/event/toggleweb/<?=$oEvent->Event_ID?>" class="btn btn-default btn-modal-mode" title="<?=$sIconTitle?>" data-hook-after="eventToggleWebModal">
                    <i class="fas <?=$sIcon?>"></i>
                </a>
                <?php } ?>

                <?php
                if(array_key_exists('wordpress',$aPlugins)) {
                    $sIcon = 'fa-bell';
                    $sIconTitle = 'Highlight auf Webseite';
                    if($oEvent->web_spotlight == 0) {
                        $sIcon = 'fa-bell-slash';
                        $sIconTitle = 'Kein Highlight auf Webseite';
                    }
                    ?>
                    <a href="/calendar/event/togglewebspotlight/<?=$oEvent->Event_ID?>" class="btn btn-default btn-modal-mode" title="<?=$sIconTitle?>" data-hook-after="eventToggleWebSpotModal">
                        <i class="fas <?=$sIcon?>"></i>
                    </a>
                <?php } ?>

                <a href="/calendar/event/edit/<?=$oEvent->Event_ID?>" class="btn btn-primary modalEditLink">
                    <i class="fas fa-edit"></i>
                </a>
                <a href="/calendar/event/delete/<?=$oEvent->Event_ID?>-<?=$sGoTo?>" class="btn btn-danger">
                    <i class="fas fa-trash"></i>
                </a>
            </div>
            </form>
        </div>
</div>
<script>
<?php if($sMode == 'modal') { ?>
    $('.modalEditLink').on('click',function() {
        $('.modal-footer').hide().after('<div class="modal-footer"><input type="submit" class="quickEditSave btn btn-success" value="Änderungen speichern" /></div>');
        $.post('/calendar/event/quickedit/<?=$oEvent->Event_ID?>',{goto:'<?=$sGoTo?>'},function(retHTML) {
            $('.dateRow').html(retHTML);
            /**
            $('.quickEditSave').on('click',function() {
               var eventID = $('#quickEditID').val();
               var date = $('#quickedit_date').val()+' '+$('#quickedit_time').val();
               $.post('/calendar/event/update',{event_id:eventID,date:date},function(retVal) {
                   window.location.reload();
               });
            }); **/
        });
        return false;
    });
    $('.eventAddTicketModal').on('click',function() {
        var iTicketID = $(this).attr('href').substring('#'.length);
        $.post('/calendar/event/addticket/'+iTicketID,{},function(retForm) {
            $('.modal-body').html(retForm);
        });

       return false;
    });
    $('.eventTicketEditModal').on('click',function() {
        var iTicketID = $(this).attr('href').substring('#'.length);
        $.post('/calendar/event/editticket/'+iTicketID,{},function(retForm) {
            $('.modal-body').html(retForm);
        });

        return false;
    });

    $('.eventEditRepeatModal').on('click',function() {
        $('.eventChildrenList li').each(function() {
            var iChildID = $(this).attr('data-child-id');
           $(this).append('<a class="btn-modal-mode" href="/calendar/event/rmchild/'+iChildID+'" data-hook-after="eventRmChildModal"><i class="fas fa-trash"></i></a>');
        });
        return false;
    });

    $('.plc-calendar-event-excerpt-modal').on('dblclick',function() {
        var text = $(this).html();
        var sEdit = '<div class="input-group mb-3 excerptQuickEditFrame">\n' +
            '  <input type="text" id="plcCalendarQuickEditExcerpt" class="form-control" placeholder="Excerpt" aria-label="Excerpt" aria-describedby="basic-addon2" value="'+text+'">\n' +
            '  <div class="input-group-append">\n' +
            '    <span class="input-group-text" id="basic-addon2"><i class="fas fa-save plcCalendarQuickEditSaveExcerpt"></i></span>\n' +
            '  </div>\n' +
            '</div>';
        $(this).replaceWith(sEdit);
    });

    $('.plc-calendar-event-description-modal').on('dblclick',function() {
        var text = $(this).html();
        var sEdit = '<div class="input-group mb-3 descriptionQuickEditFrame">\n' +
            '  <textarea id="plcCalendarQuickEditDescription" class="form-control" placeholder="Description" aria-label="Description" aria-describedby="basic-addon3">'+text+'</textarea>\n' +
            '  <div class="input-group-append">\n' +
            '    <span class="input-group-text" id="basic-addon3"><i class="fas fa-save plcCalendarQuickEditSaveDesc"></i></span>\n' +
            '  </div>\n' +
            '</div>';
        $(this).replaceWith(sEdit);
    });

    $(document).on('click','.plcCalendarQuickEditSaveExcerpt',function() {
        var newExcerpt = $('#plcCalendarQuickEditExcerpt').val();
        var eventID = $('#quickEditID').val();

        $.post('/calendar/event/update',{event_id:eventID,quickedit_excerpt:newExcerpt,mode:'modal'},function(retVal) {
            $('.excerptQuickEditFrame').replaceWith('<i class="plc-calendar-event-excerpt-modal">'+newExcerpt+'</i>');
        });

        return false;
    });

    $(document).on('click','.plcCalendarQuickEditSaveDesc',function() {
        var newDesc = $('#plcCalendarQuickEditDescription').val();
        var eventID = $('#quickEditID').val();

        $.post('/calendar/event/update',{event_id:eventID,quickedit_description:newDesc,mode:'modal'},function(retVal) {
            $('.descriptionQuickEditFrame').replaceWith('<span class="plc-calendar-event-description-modal">'+newDesc+'</span>');
        });

        return false;
    });

    $('#eventModalTitle').on('dblclick',function() {
        var text = $(this).html();
        var sEdit = '<div class="input-group mb-3 titleQuickEditFrame">\n' +
            '  <input type="text" id="plcCalendarQuickEditTitle" class="form-control" placeholder="Title" aria-label="Title" aria-describedby="basic-addon-title" value="'+text+'" />' +
            '  <div class="input-group-append">\n' +
            '    <span class="input-group-text" id="basic-addon-title"><i class="fas fa-save plcCalendarQuickEditSaveTitle"></i></span>\n' +
            '  </div>\n' +
            '</div>';
        $(this).replaceWith(sEdit);
    });

    $(document).on('click','.plcCalendarQuickEditSaveTitle',function() {
        var newTitle = $('#plcCalendarQuickEditTitle').val();
        var eventID = $('#quickEditID').val();

        $.post('/calendar/event/update',{event_id:eventID,quickedit_title:newTitle,mode:'modal'},function(retVal) {
            $('.titleQuickEditFrame').replaceWith('<h5 class="modal-title" id="eventModalTitle">'+newTitle+'</h5>');
        });

        return false;
    });

<?php } ?>
</script>