<?php
/**
 * add.phtml - Add Calendar
 *
 * View File for Add Calendar Form
 *
 * @category View
 * @package Calendar
 * @author Nathanael Kammermann
 * @copyright (C) 2019 Nathanael Kammermann <nathanael.kammermann@gmail.com>
 * @license https://opensource.org/licenses/BSD-3-Clause
 * @version 1.0
 * @since File available since Version 1.0
 */

$title = $this->translate('Add new calendar');
$this->headTitle($title);

// This provides a default CSS class and placeholder text for the title element:
$oLabel = $form->get('label');
$oLabel->setAttribute('class', 'form-control');
$oLabel->setAttribute('placeholder', 'Label');

// This provides a default CSS class and placeholder text for the artist element:
$oDesc = $form->get('description');
$oDesc->setAttribute('class', 'form-control');
$oDesc->setAttribute('placeholder', 'Description');

if(array_key_exists('fieldname',$aPlugins)) {
    $sArtRefNr = $form->get('fieldname');
    $sArtRefNr->setAttribute('class', 'form-control');
    $sArtRefNr->setAttribute('placeholder', 'Field-Name');
}

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('calendar', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form); ?>
<div class="card">
    <div class="card-header">
        <h2 class="card-title"><?=$title?></h2>
    </div>
    <div class="card-body">
        <div class="form-group">
            <?= $this->formLabel($oLabel) ?>
            <?= $this->formElement($oLabel) ?>
            <?= $this->formElementErrors()->render($oLabel, ['class' => 'help-block']) ?>
        </div>

        <?php
        // Plugins
        if(array_key_exists('plugin_name',$aPluginForms)) {

            ?>

            <?php
            //echo $this->formHidden($oCalendarIDFS);
        }
        ?>

        <div class="form-group">
            <?= $this->formLabel($oDesc) ?>
            <?= $this->formElement($oDesc) ?>
            <?= $this->formElementErrors()->render($oDesc, ['class' => 'help-block']) ?>
        </div>

        <?php if(array_key_exists('fieldname',$aPlugins)) { ?>
            <div class="form-group">
                <?= $this->formLabel($sArtRefNr) ?>
                <?= $this->formElement($sArtRefNr) ?>
                <?= $this->formElementErrors()->render($sArtRefNr, ['class' => 'help-block']) ?>
            </div>
        <?php } ?>
    </div>
    <div class="card-footer">
        <?php
        echo $this->formSubmit($submit);
        echo $this->formHidden($form->get('Calendar_ID'));
        ?>
        <a href="<?=$this->url('calendar')?>" title="<?=$this->translate('Cancel')?>" class="btn btn-danger">
            <?=$this->translate('Cancel')?>
        </a>
    </div>
</div>
<?=$this->form()->closeTag();?>
