<?php
/**
 * edit.phtml - Edit Calendar
 *
 * View File for Edit Calendar Form
 *
 * @category View
 * @package Calendar
 * @author Nathanael Kammermann
 * @copyright (C) 2019 Nathanael Kammermann <nathanael.kammermann@gmail.com>
 * @license https://opensource.org/licenses/BSD-3-Clause
 * @version 1.0
 * @since File available since Version 1.0
 */

$title = 'Edit calendar';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$oLabel = $form->get('label');
$oLabel->setAttribute('class', 'form-control');
$oLabel->setAttribute('placeholder', 'Label');

$oDesc = $form->get('description');
$oDesc->setAttribute('class', 'form-control');
$oDesc->setAttribute('placeholder', 'Description');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('calendar', [
    'action' => 'edit',
    'id'     => $id,
]));

$oCalendarID = $form->get('Calendar_ID');
$oCalendarID->setValue($id);

$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($oLabel) ?>
        <?= $this->formElement($oLabel) ?>
        <?= $this->formElementErrors()->render($oLabel, ['class' => 'help-block']) ?>
    </div>

    <?php
    // Plugins
    if(array_key_exists('plugin_name',$aPluginForms)) {
        
        ?>
        
        <?php
        //echo $this->formHidden($oCalendarIDFS);
        //echo $this->formHidden($oAddressID);
    }
    ?>

    <div class="form-group">
        <?= $this->formLabel($oDesc) ?>
        <?= $this->formElement($oDesc) ?>
        <?= $this->formElementErrors()->render($oDesc, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($oCalendarID);
echo $this->form()->closeTag();?>
