<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 05.07.2019
 * Time: 20:49
 */
?>
<div class="row">
    <div class="col-md-12">
        <div id='calendar'></div>
    </div>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">

</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
            plugins: [ 'interaction', 'resourceTimeline', 'bootstrap'],
            timeZone: 'UTC',
            maxTime: '<?=$sMaxTime?>',
            minTime: '<?=$sMinTime?>',
            defaultView: 'resourceTimelineDay',
            schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source',
            aspectRatio: 1.5,
            themeSystem: 'bootstrap',
            eventClick: function(info) {
                $.post('/calendar/event/view/'+info.event.id,{mode:'modal',goto:'residentdayplan'},function(retModal) {
                    $('#exampleModalCenter').html(retModal);
                    $('#exampleModalCenter').modal('toggle');
                });
            },
            dateClick: function(info) {
                var sDateSelected = info.dateStr;
                //alert(sDateSelected);
                var iResidentID = info.resource.id;
                $.get('/resident/event/add/'+iResidentID+'-resident',{mode:'modal',date:sDateSelected,goto:'residentdayplan'},function(retModal) {
                    $('#exampleModalCenter').html(retModal);
                    $('#exampleModalCenter').modal('toggle');
                });

                //alert('Clicked on: ' + info.dateStr);
                //alert('resident: ' + info.resource.id);
                //alert('resident: ' + info.resource.id);
                // change the day's background color just for fun
                //info.dayEl.style.backgroundColor = 'red';
            },
            header: {
                left: 'prev,next',
                center: 'title',
                right: 'resourceTimelineDay,resourceTimelineWeek,resourceTimelineMonth'
            },
            locale: 'de',
            nowIndicator: true,
            editable: true,
            resourceLabelText: 'Rooms',
            resources: <?=json_encode($aResiList)?>,
            eventSources: <?=json_encode($aEventSources)?>
        });

        calendar.render();
    });

</script>