<?php
/**
 * view.phtml - View Calendar
 *
 * View File for View Calendar Form
 *
 * @category View
 * @package Calendar
 * @author Nathanael Kammermann
 * @copyright (C) 2019 Nathanael Kammermann <nathanael.kammermann@gmail.com>
 * @license https://opensource.org/licenses/BSD-3-Clause
 * @version 1.0
 * @since File available since Version 1.0
 */

$title = 'View calendar';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$oLabel = $form->get('label');
$oLabel->setAttribute('class', 'form-control');
$oLabel->setAttribute('placeholder', 'Label');

$oDescription = $form->get('description');
$oDescription->setAttribute('class', 'form-control');
$oDescription->setAttribute('placeholder', 'Description');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('calendar', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();
?>
<div class="form-group">
    <?=$oLabel->getLabel()?><br/>
    <?=$oLabel->getValue()?>
</div>

<div class="form-group">
    <?=$oDescription->getLabel()?><br/>
    <?=$oDescription->getValue()?>
</div>

<?php
if(array_key_exists('plugin_name',$aPlugins)) {
?>
    Print Plugin
<?php
}
?>
<?php if($this->layout()->oUser->hasPermission('edit','Calendar')) { ?>
<a class="btn btn-primary" href="<?= $this->url('calendar', ['action' => 'edit', 'id' => $id]) ?>"><?=$this->translate('Edit')?></a>
<?php } ?>
<?php if($this->layout()->oUser->hasPermission('delete','Calendar')) { ?>
<a class="btn btn-danger" href="<?= $this->url('calendar', ['action' => 'delete', 'id' => $id]) ?>"><?=$this->translate('Delete')?></a>
<?php } ?>
